version: '3.2'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /var/www/
    container_name: php-amzmp
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php_conf.ini
    networks:
      - amzmp_backend

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver-nginx-amzmp
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - amzmp_backend

  mysql:
    image: 'mysql:8.0.30'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}

    volumes:
      - './.docker/mysql:/var/lib/mysql'
    networks:
      - amzmp_backend

networks:
  amzmp_backend:
    driver: bridge
